#+TITLE: SICP 学习笔记：程序构造与解释
#+SUMMARY: 深入探索计算机程序的构造和解释，从表达式到抽象。
#+DATE: 2026-05-30
#+LABELS: lisp:scheme:sicp
#+DRAFT: false

* 1.1 The Elements of Programming

A powerful programming language is more than just a means for instructing a computer to perform tasks. The language also serves as a framework within which we organize our ideas about processes. Thus, when we describe a language, we should pay particular attention to the means that the language provides for combining simple ideas to form more complex ideas. Every powerful language has three mechanisms for accomplishing this:

- *primitive expressions*, which represent the simplest entities the language is concerned with,
- *means of combination*, by which compound elements are built from simpler ones, and
- *means of abstraction*, by which compound elements can be named and manipulated as units.

** 1.1.1 Expressions

One easy way to get started at programming is to examine some typical interactions with an interpreter for the Scheme dialect of Lisp. Imagine that you are sitting at a computer terminal. You type an /expression/, and the interpreter responds by displaying the result of its /evaluating/ that expression.

One kind of primitive expression you might type is a number.

#+BEGIN_SRC scheme :interactive
486
#+END_SRC

Expressions representing numbers may be combined with an expression representing a primitive procedure (such as ~+~ or ~*~) to form a compound expression that represents the application of the procedure to those numbers. For example:

#+BEGIN_SRC scheme :interactive
(+ 137 349)
#+END_SRC

#+BEGIN_SRC scheme :interactive
(- 1000 334)
#+END_SRC

#+BEGIN_SRC scheme :interactive
(* 5 99)
#+END_SRC

#+BEGIN_SRC scheme :interactive
(/ 10 5)
#+END_SRC

** 1.1.2 Naming and the Environment

A critical aspect of a programming language is the means it provides for using names to refer to computational objects. We say that the name identifies a /variable/ whose /value/ is the object.

In the Scheme dialect of Lisp, we name things with ~define~.

#+BEGIN_SRC scheme :interactive
(define size 2)
size
#+END_SRC

#+BEGIN_SRC scheme :interactive
(* 5 size)
#+END_SRC

Here are further examples of the use of ~define~:

#+BEGIN_SRC scheme :interactive
(define pi 3.14159)
(define radius 10)
(* pi (* radius radius))
#+END_SRC

** 1.1.3 Evaluating Combinations

To evaluate a combination, do the following:

1. Evaluate the subexpressions of the combination.
2. Apply the procedure that is the value of the leftmost subexpression (the operator) to the arguments that are the values of the other subexpressions (the operands).

#+BEGIN_SRC scheme :interactive
(* (+ 2 (* 4 6)) (+ 3 5 7))
#+END_SRC

Viewing evaluation in terms of a tree, we can imagine that the values of the operands percolate upward, starting from the terminal nodes and then combining at higher and higher levels. This general kind of process is known as /tree accumulation/.
